# Generated by Django 5.1.1 on 2025-06-24 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('risk_classification', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegulatoryFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FrameworkSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(choices=[('EU_AI_ACT', 'EU AI Act'), ('NIST_RMF', 'NIST AI RMF'), ('CPRA', 'CPRA')], max_length=50)),
                ('analysis_status', models.CharField(default='PENDING', max_length=50)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance_app.document')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='compliance_app.regulatoryframework')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance_app.document')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance_app.regulatoryframework')),
                ('related_requirements', models.ManyToManyField(blank=True, to='compliance_app.requirement')),
            ],
        ),
    ]
