version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.local
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
      - GEMINI_API_KEY=AIzaSyDGZoBl8q00PF5Nd2XIQIlKWi_Ju7d30X8
      - MONGO_URI=mongodb+srv://maxdefanti:vytsf38rBFxM1GQ6@governaice.q68lcpg.mongodb.net/?retryWrites=true&w=majority&appName=GovernAIce
      - MONGO_DB_NAME=Training
      - TOGETHER_API_KEY=2150c44b537a788818aa55f7fe669c44623f946dbf3d06cc4b8e1a6d1f04bb3e

    env_file:
      - ../backend/.env
    networks:
      - app-network
    volumes:
      - ../backend:/app/backend
      - ../ml:/app/ml
      - ../main.py:/app/main.py
    command: python backend/app.py

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5001
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
