version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.local
    ports:
      - "5001:5002"
    environment:
      - FLASK_ENV=development
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    env_file:
      - ../backend/.env
    networks:
      - app-network
    volumes:
      - ../backend:/app/backend
      - ../ml:/app/ml
      - ../main.py:/app/main.py
    command: python backend/app.py

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5001
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
