version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "5001:5000"  # Host 5001 -> Container 5000 (Flask)
    environment:
      - FLASK_ENV=development
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    depends_on:
      - mongodb
    volumes:
      - ../backend:/app/backend
      - ../ml:/app/ml
      - ../main.py:/app/main.py
    command: python backend/app.py

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    volumes:
      - ../frontend:/app
      - /app/node_modules      # Anonymous volume for container-only node_modules
    environment:
      - VITE_API_URL=http://localhost:5001
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
