version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.local
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - GEMINI_API_KEY=${GEMINI_API_KEY:-your_gemini_api_key_here}
      - MONGO_URI=mongodb+srv://hheidy463:Heidy_463@governaice.q68lcpg.mongodb.net/?retryWrites=true&w=majority&appName=GovernAIce
      - MONGO_DB_NAME=Training
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - ../backend:/app/backend
      - ../ml:/app/ml
      - ../main.py:/app/main.py
    command: python backend/app.py

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5001
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
